version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: refinedwiki/node-with-java
      #- image: node:6.10.2-slim
      #- image: openjdk:jre
      #- image: selenium/standalone-chrome:3.1.0
    steps:
      - checkout
      - restore_cache:
          key: angularclosure-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: node --version
      - run: yarn --version
      - run: java -version
      - run: yarn
      - run: yarn run build
      - run: yarn test
      - save_cache:
          key: angularclosure-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"